build: off
cache: "c:\\sr -> appveyor.yml"

test_script:
- ps: Invoke-Expression (Invoke-WebRequest 'https://raw.githubusercontent.com/ndmitchell/neil/master/appveyor.ps1')
- stack exec -- hoogle generate --insecure
- stack exec -- hoogle test
